gatewell:
  auth:
    enabled: true

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/gatewell}
    username: ${DATABASE_USERNAME:gatewell}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
